package bemlyCJWeb.posts

import html_builder.*
import bemlyCJWeb.model.*

public func getCpu51ctotm5800Post(): Post {
    return Post(
        "cpu51ctotm5800",
        "评论：全美达不玩CPU了_51CTO博客_全美达tm5800",
        "2023-08-03",
        "原文待补充：评论：全美达不玩CPU了_51CTO博客_全美达tm5800",
        { b =>
            h2(b, "评论：全美达不玩CPU了_51CTO博客_全美达tm5800")
            p(b, "原文内容待补充。")
            a(b, attrs("href", "https://blog.51cto.com/maray/6492928"), "阅读原文")
        }
    )
}
