package bemlyCJWeb.posts

import html_builder.*
import bemlyCJWeb.model.*

public func getDortaniaopencoreLegacyPatcherExperienceMaPost(): Post {
    return Post(
        "dortaniaopencore-legacy-patcher-experience-ma",
        "dortania/OpenCore-Legacy-Patcher: Experience ma...",
        "2024-02-14",
        "GitHub 仓库：dortania/OpenCore-Legacy-Patcher: Experi",
        { b =>
            h2(b, "dortania/OpenCore-Legacy-Patcher: Experience ma...")
            p(b, "此链接为 GitHub 仓库，非博客文章。")
            a(b, attrs("href", "https://github.com/dortania/OpenCore-Legacy-Patcher"), "访问原始链接")
        }
    )
}
