package bemlyCJWeb.posts

import html_builder.*
import bemlyCJWeb.model.*

public func getIllixionvscodeVibrancyContinuedEnableAcryPost(): Post {
    return Post(
        "illixionvscode-vibrancy-continued-enable-acry",
        "illixion/vscode-vibrancy-continued: Enable Acry...",
        "2024-11-19",
        "GitHub 仓库：illixion/vscode-vibrancy-continued: Enab",
        { b =>
            h2(b, "illixion/vscode-vibrancy-continued: Enable Acry...")
            p(b, "此链接为 GitHub 仓库，非博客文章。")
            a(b, attrs("href", "https://github.com/illixion/vscode-vibrancy-continued"), "访问原始链接")
        }
    )
}
