package bemlyCJWeb.posts

import html_builder.*
import bemlyCJWeb.model.*

public func getJerryjliullamaindexLlamaindexGptIndexIPost(): Post {
    return Post(
        "jerryjliullamaindex-llamaindex-gpt-index-i",
        "jerryjliu/llama_index: LlamaIndex (GPT Index) i...",
        "2023-04-05",
        "GitHub 仓库：jerryjliu/llama_index: LlamaIndex (GPT I",
        { b =>
            h2(b, "jerryjliu/llama_index: LlamaIndex (GPT Index) i...")
            p(b, "此链接为 GitHub 仓库，非博客文章。")
            a(b, attrs("href", "https://github.com/jerryjliu/llama_index"), "访问原始链接")
        }
    )
}
