package bemlyCJWeb.posts

import html_builder.*
import bemlyCJWeb.model.*

public func getLiteloaderqqntqqntfileverifypatchQqntPaPost(): Post {
    return Post(
        "liteloaderqqntqqntfileverifypatch-qqnt-pa",
        "LiteLoaderQQNT/QQNTFileVerifyPatch: 逆他妈的QQNT Pa...",
        "2024-08-18",
        "GitHub 仓库：LiteLoaderQQNT/QQNTFileVerifyPatch: 逆他妈的",
        { b =>
            h2(b, "LiteLoaderQQNT/QQNTFileVerifyPatch: 逆他妈的QQNT Pa...")
            p(b, "此链接为 GitHub 仓库，非博客文章。")
            a(b, attrs("href", "https://github.com/LiteLoaderQQNT/QQNTFileVerifyPatch"), "访问原始链接")
        }
    )
}
