package bemlyCJWeb.posts

import html_builder.*
import bemlyCJWeb.model.*

public func getMouse0w0minecraftdeveloperguideMinecraftDePost(): Post {
    return Post(
        "mouse0w0minecraftdeveloperguide-minecraft-de",
        "mouse0w0/MinecraftDeveloperGuide: 📝Minecraft de...",
        "2024-12-26",
        "GitHub 仓库：mouse0w0/MinecraftDeveloperGuide: 📝Minec",
        { b =>
            h2(b, "mouse0w0/MinecraftDeveloperGuide: 📝Minecraft de...")
            p(b, "此链接为 GitHub 仓库，非博客文章。")
            a(b, attrs("href", "https://github.com/mouse0w0/MinecraftDeveloperGuide"), "访问原始链接")
        }
    )
}
