package bemlyCJWeb.posts

import html_builder.*
import bemlyCJWeb.model.*

public func getNukepayload2nukepayload2sourcegeneratorsavalPost(): Post {
    return Post(
        "nukepayload2nukepayload2sourcegeneratorsaval",
        "Nukepayload2/Nukepayload2.SourceGenerators.Aval...",
        "2024-08-28",
        "GitHub 仓库：Nukepayload2/Nukepayload2.SourceGenerato",
        { b =>
            h2(b, "Nukepayload2/Nukepayload2.SourceGenerators.Aval...")
            p(b, "此链接为 GitHub 仓库，非博客文章。")
            a(b, attrs("href", "https://github.com/Nukepayload2/Nukepayload2.SourceGenerators.AvaloniaUI"), "访问原始链接")
        }
    )
}
