package bemlyCJWeb.posts

import html_builder.*
import bemlyCJWeb.model.*

public func getNukepayload2avaloniaVbnetTemplatesAvaloniaPost(): Post {
    return Post(
        "nukepayload2avalonia-vbnet-templates-avalonia",
        "Nukepayload2/avalonia-vbnet-templates: Avalonia...",
        "2024-12-25",
        "GitHub 仓库：Nukepayload2/avalonia-vbnet-templates: A",
        { b =>
            h2(b, "Nukepayload2/avalonia-vbnet-templates: Avalonia...")
            p(b, "此链接为 GitHub 仓库，非博客文章。")
            a(b, attrs("href", "https://github.com/Nukepayload2/avalonia-vbnet-templates"), "访问原始链接")
        }
    )
}
