package bemlyCJWeb.posts

import html_builder.*
import bemlyCJWeb.model.*

public func getPalera1npalera1nJailbreakForA8ThroughA11Post(): Post {
    return Post(
        "palera1npalera1n-jailbreak-for-a8-through-a11",
        "palera1n/palera1n: Jailbreak for A8 through A11...",
        "2025-03-03",
        "GitHub 仓库：palera1n/palera1n: Jailbreak for A8 thro",
        { b =>
            h2(b, "palera1n/palera1n: Jailbreak for A8 through A11...")
            p(b, "此链接为 GitHub 仓库，非博客文章。")
            a(b, attrs("href", "https://github.com/palera1n/palera1n"), "访问原始链接")
        }
    )
}
