package bemlyCJWeb.posts

import html_builder.*
import bemlyCJWeb.model.*

public func getRaindropCreactNativeWebviewTencentx5AndPost(): Post {
    return Post(
        "raindrop-creact-native-webview-tencentx5-and",
        "RainDrop-C/react-native-webview-tencentx5: 将And...",
        "2022-06-21",
        "GitHub 仓库：RainDrop-C/react-native-webview-tencentx",
        { b =>
            h2(b, "RainDrop-C/react-native-webview-tencentx5: 将And...")
            p(b, "此链接为 GitHub 仓库，非博客文章。")
            a(b, attrs("href", "https://github.com/RainDrop-C/react-native-webview-tencentx5"), "访问原始链接")
        }
    )
}
