package bemlyCJWeb.posts

import html_builder.*
import bemlyCJWeb.model.*

public func getReleasesAnlostsheephackintoshColorfulB460iPost(): Post {
    return Post(
        "releases-anlostsheephackintosh-colorful-b460i",
        "Releases · anlostsheep/hackintosh-colorful-b460i",
        "2024-10-10",
        "GitHub 仓库：Releases · anlostsheep/hackintosh-colorf",
        { b =>
            h2(b, "Releases · anlostsheep/hackintosh-colorful-b460i")
            p(b, "此链接为 GitHub 仓库，非博客文章。")
            a(b, attrs("href", "https://github.com/anlostsheep/hackintosh-colorful-b460i"), "访问原始链接")
        }
    )
}
