package bemlyCJWeb.posts

import html_builder.*
import bemlyCJWeb.model.*

public func getSqlsecasrockZ490SteelLegendI710700AsrocPost(): Post {
    return Post(
        "sqlsecasrock-z490-steel-legend-i7-10700-asroc",
        "sqlsec/AsRock-Z490-Steel-Legend-i7-10700: ASRoc...",
        "2024-02-17",
        "GitHub 仓库：sqlsec/AsRock-Z490-Steel-Legend-i7-10700",
        { b =>
            h2(b, "sqlsec/AsRock-Z490-Steel-Legend-i7-10700: ASRoc...")
            p(b, "此链接为 GitHub 仓库，非博客文章。")
            a(b, attrs("href", "https://github.com/sqlsec/AsRock-Z490-Steel-Legend-i7-10700"), "访问原始链接")
        }
    )
}
