package bemlyCJWeb.posts

import html_builder.*
import bemlyCJWeb.model.*

public func getTfjsModelsposeDetectionsrcmovenetAtMastePost(): Post {
    return Post(
        "tfjs-modelspose-detectionsrcmovenet-at-maste",
        "tfjs-models/pose-detection/src/movenet at maste...",
        "2024-02-01",
        "GitHub 文件：tfjs-models/pose-detection/src/movenet a",
        { b =>
            h2(b, "tfjs-models/pose-detection/src/movenet at maste...")
            p(b, "此链接为 GitHub 文件/代码，非博客文章。")
            a(b, attrs("href", "https://github.com/tensorflow/tfjs-models/tree/master/pose-detection/src/movenet"), "访问原始链接")
        }
    )
}
