package bemlyCJWeb.posts

import html_builder.*
import bemlyCJWeb.model.*

public func getUcjsCollectionsDupontjoycingfoxAtMasterPost(): Post {
    return Post(
        "ucjs-collections-dupontjoycingfox-at-master",
        "uc.js-Collections-dupontjoy/CingFox at master ·...",
        "2021-10-16",
        "GitHub 文件：uc.js-Collections-dupontjoy/CingFox at m",
        { b =>
            h2(b, "uc.js-Collections-dupontjoy/CingFox at master ·...")
            p(b, "此链接为 GitHub 文件/代码，非博客文章。")
            a(b, attrs("href", "https://github.com/xinggsf/uc.js-Collections-dupontjoy/tree/master/CingFox"), "访问原始链接")
        }
    )
}
