package bemlyCJWeb.posts

import html_builder.*
import bemlyCJWeb.model.*

public func getUos6546751ctoPost(): Post {
    return Post(
        "uos6546751cto",
        "统信UOS中普通用户忘记密码处理方法_65467的技术博客_51CTO博客",
        "2021-09-26",
        "原文待补充：统信UOS中普通用户忘记密码处理方法_65467的技术博客_51CTO博客",
        { b =>
            h2(b, "统信UOS中普通用户忘记密码处理方法_65467的技术博客_51CTO博客")
            p(b, "原文内容待补充。")
            a(b, attrs("href", "https://blog.51cto.com/idtechOPS/2666239"), "阅读原文")
        }
    )
}
