package bemlyCJWeb.posts

import html_builder.*
import bemlyCJWeb.model.*

public func getYadavnikhil03playIntegrityFixGuideEasiestPost(): Post {
    return Post(
        "yadavnikhil03play-integrity-fix-guide-easiest",
        "yadavnikhil03/Play-integrity-fix-guide: Easiest...",
        "2026-03-06",
        "GitHub 文件：yadavnikhil03/Play-integrity-fix-guide: ",
        { b =>
            h2(b, "yadavnikhil03/Play-integrity-fix-guide: Easiest...")
            p(b, "此链接为 GitHub 文件/代码，非博客文章。")
            a(b, attrs("href", "https://github.com/yadavnikhil03/Play-integrity-fix-guide/tree/main"), "访问原始链接")
        }
    )
}
